encoder: 
  hidden_dim: 128
  num_layers: 2
  dropout: 0.1
  rnn_type: 'gru'

decoder:
  hidden_dim: 128
  num_layers: 2
  rnn_type: 'gru'

supervised:
  hidden_dims:
    - 64
    - 32

embedding: 128
